name: test
on:
  push: {}
  workflow_dispatch: {}

jobs:
  test:
    name: mocha test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: yarn install

      - name: test
        run: yarn test
